### ISSUE TITLE
How to get recursively result?

### ISSUE THREAD

**Issue by favoyang** [koresar/s3-ls#3]
For s3 content
```
my-folder/subfolder/file1
my-folder/subfolder/file2
my-folder/subfolder/subsub/file3
```

Current `lister.ls('my-folder/')` returns
```
files: []
folders: ['subfolder']
```

I would like to have `lister.ls('my-folder/', recursively=true)` returns
```
files:
  - subfolder/file1
  - subfolder/file2
  - subfolder/subsub/file3
folders:
  - subfolder
  - subfolder/subsub
```

Is this possible?

**Comment by koresar** [comment]
Yeap. That is possible. See the sibling project https://github.com/koresar/s3-tree
Tell me if it works for you.

**Comment by favoyang** [comment]
@koresar thanks for the link, work like a charm!
